#!/bin/python3

"""
This code defines a script which verifies a given ordinance PDF.
"""

# Standard imports.
import argparse

# Bespoke imports.
from chancery_b import (
    DEFAULT_PATH_TO_PUBLIC_KEY,
    verify_pdf,
    create_data_dir_as_necessary
)

#############
# FUNCTIONS #
#############

def make_parser():
    """ Make the parser object. """
    desc_str = "Verify a given ordinance-containing PDF."
    result = argparse.ArgumentParser(description=desc_str)
    result.add_argument(
        "path_to_pdf",
        help="The path to the PDF question",
        type=str
    )
    result.add_argument(
        "--path-to-public_key",
        help="The path to the file containing the public key",
        type=str,
        dest="path_to_public_key",
        default=DEFAULT_PATH_TO_PUBLIC_KEY
    )
    return result

###################
# RUN AND WRAP UP #
###################

def run():
    """ Run this file. """
    parser = make_parser()
    arguments = parser.parse_args()
    verified = \
        verify_pdf(
            arguments.path_to_pdf,
            path_to_public_key=arguments.path_to_public_key
        )
    if verified:
        print("Verified PDF at path: "+arguments.path_to_pdf)
    else:
        print("Failed to verify PDF at path: "+arguments.path_to_pdf)

if __name__ == "__main__":
    run()
